import dns from'node:dns/promises';import net from'node:net';
const UA='WorldMaxAI-AgentReadyScanner/1.0';
function privateIp(ip){const v=net.isIP(ip);if(v===4){const[a,b]=ip.split('.').map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}if(v===6){const s=ip.toLowerCase();return s==='::'||s==='::1'||/^f[cd]/.test(s)||/^fe[89ab]/.test(s)}return true}
async function safe(input){const raw=String(input||'').trim();if(!raw)throw Error('Inserisci un URL.');const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('URL non ammesso.');if(u.port&&!['80','443'].includes(u.port))throw Error('Porta non ammessa.');if(u.hostname==='localhost'||/\.(local|localhost|internal|home|lan)$/i.test(u.hostname))throw Error('Host locale non ammesso.');if(net.isIP(u.hostname)){if(privateIp(u.hostname))throw Error('IP privato non ammesso.')}else{const r=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!r.length||r.some(x=>privateIp(x.address)))throw Error('Dominio non pubblico.')}u.hash='';return u}
async function get(input,max=500000){let u=await safe(input);for(let i=0;i<5;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);let r;try{r=await fetch(u,{redirect:'manual',signal:c.signal,headers:{'user-agent':UA,accept:'application/json,text/html,text/plain,application/yaml,application/xml;q=.8,*/*;q=.1'}})}finally{clearTimeout(t)}if([301,302,303,307,308].includes(r.status)){const l=r.headers.get('location');if(!l)throw Error('Redirect non valido.');u=await safe(new URL(l,u).href);continue}const len=Number(r.headers.get('content-length')||0);if(len>max)throw Error('Risorsa troppo grande.');return{ok:r.ok,status:r.status,url:u.href,type:r.headers.get('content-type')||'',text:(await r.text()).slice(0,max)}}throw Error('Troppi redirect.')}
async function maybe(url,max){try{return await get(url,max)}catch(e){return{ok:false,status:0,url:String(url),type:'',text:'',error:e.message}}}
function attr(tag,n){const m=new RegExp(`\\b${n}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`,'i').exec(tag);return m?.[1]??m?.[2]??m?.[3]??''}
function htmlCatalog(html,base){for(const tag of html.match(/<link\b[^>]*>/gi)||[]){const rel=attr(tag,'rel').toLowerCase().split(/\s+/);if(rel.includes('ai-catalog')){try{const u=new URL(attr(tag,'href'),base);if(u.hostname===new URL(base).hostname)return u.href}catch{}}}return null}
function robotsCatalog(text,base){for(const line of String(text||'').split(/\r?\n/)){const m=/^\s*Agentmap\s*:\s*(\S+)/i.exec(line.replace(/#.*$/,''));if(m)try{const u=new URL(m[1],base);if(u.hostname===new URL(base).hostname)return u.href}catch{}}return null}
function parseJson(r){if(!r?.ok)return null;try{return JSON.parse(r.text)}catch{return null}}
function catalogEntries(x){return Array.isArray(x?.entries)?x.entries:[]}
function entryUrl(e){return e?.url||e?.endpoint||e?.location||null}
function detectFromCatalog(cat){const out={mcp:null,a2a:null,openApi:null};for(const e of catalogEntries(cat)){const t=String(e?.type||e?.mediaType||'').toLowerCase(),caps=JSON.stringify(e?.capabilities||[]).toLowerCase(),u=entryUrl(e);if(!u)continue;if(!out.mcp&&(t.includes('mcp')||caps.includes('mcp')))out.mcp=u;if(!out.a2a&&(t.includes('a2a')||caps.includes('a2a')))out.a2a=u;if(!out.openApi&&(t.includes('openapi')||t.includes('oai.openapi')||caps.includes('openapi')))out.openApi=u}return out}
export default async function handler(req,res){res.setHeader('cache-control','no-store');res.setHeader('content-type','application/json; charset=utf-8');if(req.method!=='POST')return res.status(405).json({error:'Usa POST.'});try{const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),root=await safe(b.url),home=await get(root.href,900000);if(!home.ok||!/html/i.test(home.type||'text/html'))throw Error(`Homepage non analizzabile (HTTP ${home.status}).`);const base=new URL(home.url),robots=await maybe(new URL('/robots.txt',base).href,250000);const catalogCandidates=[htmlCatalog(home.text,base.href),robotsCatalog(robots.text,base.href),new URL('/.well-known/ai-catalog.json',base).href].filter(Boolean);let catalogResponse=null,catalogUrl=null,catalog=null;for(const u of [...new Set(catalogCandidates)]){const r=await maybe(u,600000),j=parseJson(r);if(r.ok&&j){catalogResponse=r;catalogUrl=r.url;catalog=j;break}}
const [agentCardRaw,openApiRaw,swaggerRaw]=await Promise.all([maybe(new URL('/.well-known/agent-card.json',base).href,500000),maybe(new URL('/openapi.json',base).href,900000),maybe(new URL('/swagger.json',base).href,900000)]);const agentCard=parseJson(agentCardRaw),openApi=parseJson(openApiRaw)||parseJson(swaggerRaw);const fromCatalog=detectFromCatalog(catalog);const endpoints={aiCatalog:catalogUrl||null,agentCard:agentCard?agentCardRaw.url:(fromCatalog.a2a||null),openApi:openApi?(parseJson(openApiRaw)?openApiRaw.url:swaggerRaw.url):(fromCatalog.openApi||null),mcp:fromCatalog.mcp||null};const signals={ard:Boolean(catalog),agentCard:Boolean(endpoints.agentCard),openApi:Boolean(endpoints.openApi),mcp:Boolean(endpoints.mcp),ucp:false};return res.status(200).json({version:'1.0.0',url:base.href,hostname:base.hostname,signals,endpoints,discovery:{aiCatalog:{detected:Boolean(catalog),url:catalogUrl,via:catalogUrl===htmlCatalog(home.text,base.href)?'html-link':catalogUrl===robotsCatalog(robots.text,base.href)?'robots-agentmap':catalogUrl?'well-known':null,entryCount:catalogEntries(catalog).length},agentCard:{detected:Boolean(agentCard),status:agentCardRaw.status,url:agentCard?agentCardRaw.url:null},openApi:{detected:Boolean(openApi),status:openApiRaw.ok?openApiRaw.status:swaggerRaw.status,url:endpoints.openApi},mcp:{detected:Boolean(endpoints.mcp),source:endpoints.mcp?'ARD catalog':null,url:endpoints.mcp},robots:{status:robots.status}},catalog:catalog?{specVersion:catalog.specVersion||null,entryCount:catalogEntries(catalog).length}:null});}catch(e){return res.status(400).json({error:e.message||'Discovery fallita.'})}}
