import dns from 'node:dns/promises';
import net from 'node:net';
import {fact,isStrongAction,resolveIdentity,classifyVertical,deriveCapabilities,scoreReadiness,buildSkill,validateReportSkillParity} from '../lib/evidence-engine-v12.js';

const UA='WorldMaxAI-AgentReadyScanner/1.2';
const MAX_PAGES=6;
const CHALLENGE=/(?:verify that you(?:'|’)re not a robot|javascript is disabled|enable javascript.*reload|captcha|unusual traffic|access denied|robot check)/i;
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const clean=s=>String(s||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
const one=(h,r)=>{const m=r.exec(h);return m?clean(m[1]):''};
function attr(tag,n){const m=new RegExp(`\\b${n}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`,'i').exec(tag);return m?.[1]??m?.[2]??m?.[3]??''}
function privateIp(ip){const v=net.isIP(ip);if(v===4){const[a,b]=ip.split('.').map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224}if(v===6){const s=ip.toLowerCase();return s==='::'||s==='::1'||/^f[cd]/.test(s)||/^fe[89ab]/.test(s)}return true}
async function safeUrl(input){const raw=String(input||'').trim();if(!raw)throw Error('Inserisci un URL.');const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('URL non ammesso.');if(u.port&&!['80','443'].includes(u.port))throw Error('Porta non ammessa.');if(net.isIP(u.hostname)){if(privateIp(u.hostname))throw Error('IP privato non ammesso.')}else{const a=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!a.length||a.some(x=>privateIp(x.address)))throw Error('Dominio non pubblico.')}u.hash='';return u}
async function getText(input,max=1200000){let u=await safeUrl(input);for(let i=0;i<5;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);let r;try{r=await fetch(u,{redirect:'manual',signal:c.signal,headers:{'user-agent':UA,accept:'text/html,application/json,application/xml,text/plain,*/*;q=.1'}})}finally{clearTimeout(t)}if([301,302,303,307,308].includes(r.status)){const l=r.headers.get('location');if(!l)throw Error('Redirect non valido.');u=await safeUrl(new URL(l,u).href);continue}return{status:r.status,ok:r.ok,url:u.href,type:r.headers.get('content-type')||'',text:(await r.text()).slice(0,max)}}throw Error('Troppi redirect.')}
async function maybe(u,m){try{return await getText(u,m)}catch(e){return{status:0,ok:false,url:String(u),type:'',text:'',error:e.message}}}
function links(h,base){const out=new Set(),b=new URL(base);for(const m of h.matchAll(/<a\b[^>]*href\s*=\s*(?:"([^"]+)"|'([^']+)'|([^\s>]+))/gi)){try{const u=new URL(m[1]||m[2]||m[3],b);u.hash='';if(u.hostname===b.hostname&&/^https?:$/.test(u.protocol))out.add(u.href)}catch{}}return[...out]}
function jsonld(h,url){const facts=[];for(const m of h.matchAll(/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const x=JSON.parse(m[1]);const walk=o=>{if(Array.isArray(o))return o.forEach(walk);if(o&&typeof o==='object'){const ts=(Array.isArray(o['@type'])?o['@type']:[o['@type']]).filter(Boolean).map(String);for(const t of ts)facts.push(fact('schema_type',t,{source:'jsonld',url,confidence:.98}));if(typeof o.name==='string'&&o.name.trim())facts.push(fact('identity_candidate',o.name.trim(),{source:'jsonld',url,confidence:.97}));if(o.price!=null)facts.push(fact('price',String(o.price),{source:'jsonld',url,confidence:.95,meta:{currency:o.priceCurrency||null}}));Object.values(o).forEach(walk)}};walk(x)}catch{}}return facts}
function formKind(action,body,method){const names=[...body.matchAll(/<(?:input|select|textarea)\b([^>]*)>/gi)].map(m=>`${attr(m[1],'name')} ${attr(m[1],'id')} ${attr(m[1],'type')} ${attr(m[1],'placeholder')}`).join(' '),sig=`${action} ${names} ${clean(body).slice(0,500)}`;if(/captcha|validatecaptcha|recaptcha|hcaptcha|robot|challenge|verify.?human/i.test(sig))return'challenge_form';if(/(?:^|\b)(?:q|query|search|keyword|keywords|field-keywords)(?:\b|$)/i.test(names)&&method==='GET')return'search_form';if(/password|passwd|login|log.?in|sign.?in|authenticate|session/i.test(sig))return'auth_form';return'form'}
function collectPage(h,url){const facts=[fact('page',url,{source:'crawl',url,confidence:1})],title=one(h,/<title\b[^>]*>([\s\S]*?)<\/title>/i),h1=one(h,/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);if(title)facts.push(fact('identity_candidate',title.split(/[|–—]/)[0].trim(),{source:'title',url,confidence:.78}));if(h1)facts.push(fact('identity_candidate',h1,{source:'h1',url,confidence:.86}));for(const tag of h.match(/<meta\b[^>]*>/gi)||[]){const prop=attr(tag,'property'),name=attr(tag,'name'),content=attr(tag,'content');if(content&&(prop==='og:site_name'||name==='application-name'))facts.push(fact('identity_candidate',content,{source:'og',url,confidence:.94}))}facts.push(...jsonld(h,url));const text=clean(h),priceMatches=text.match(/(?:€|EUR\s?|\$|USD\s?|£|GBP\s?)\s?\d[\d.,]*/gi)||[];for(const p of uniq(priceMatches).slice(0,20))facts.push(fact('price',p,{source:'html',url,confidence:.72}));for(const m of h.matchAll(/<(button|a)\b([^>]*)>([\s\S]*?)<\/\1>/gi)){const label=clean(m[3]);if(!label||!isStrongAction(label))continue;facts.push(fact('action',label,{source:m[1].toLowerCase(),url,confidence:.88,meta:{href:attr(m[2],'href')||null}}))}for(const m of h.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/gi)){const action=attr(m[1],'action')||url,method=(attr(m[1],'method')||'GET').toUpperCase(),kind=formKind(action,m[2],method),ff=fact(kind,action,{source:'form',url,confidence:.9,meta:{method,purpose:kind.replace('_form','')}});facts.push(ff);for(const im of m[2].matchAll(/<(?:input|select|textarea)\b([^>]*)>/gi)){const n=attr(im[1],'name')||attr(im[1],'id')||attr(im[1],'placeholder');if(n)facts.push(fact('field_name',n,{source:'form-field',url,confidence:.85,meta:{formId:ff.id,formKind:kind}}))}}const signalPatterns=[/\brestaurant\b|\bristorante\b|reserve a table|book your table|discover the menu/ig,/\bhotel\b|\baccommodation\b|check[ -]?in|check[ -]?out|\brooms?\b|\bcamere\b/ig,/\bshop\b|\bshopping\b|\bproducts?\b|\bcatalogo\b|add to cart|checkout/ig];for(const re of signalPatterns){const hits=text.match(re)||[];for(const s of uniq(hits).slice(0,5))facts.push(fact('text_signal',s,{source:'html-text',url,confidence:.6}))}return{facts,links:links(h,url),text}}
async function discoverMachine(base){const defs=[['openapi','/openapi.json'],['openapi','/swagger.json'],['a2a','/.well-known/agent-card.json'],['ard','/.well-known/ai-catalog.json']];const facts=[],checks=[];for(const[k,p]of defs){const r=await maybe(new URL(p,base).href,300000);let valid=false;if(r.ok){try{JSON.parse(r.text);valid=true}catch{}}checks.push({kind:k,url:new URL(p,base).href,status:r.status,valid});if(valid)facts.push(fact('machine_interface',k,{source:'well-known',url:new URL(p,base).href,confidence:1}))}return{facts,checks}}
function inconclusive(base,evidence,reason){const identity=resolveIdentity(evidence,base.hostname),access={status:'limited',reason},capabilities=deriveCapabilities(evidence,{pagesObserved:0,accessStatus:'limited'}),readiness=scoreReadiness(evidence,capabilities,{accessStatus:'limited',pagesObserved:0}),vertical={type:'unknown / insufficient evidence',confidence:'low',scores:{},evidenceIds:[]},report={version:'1.2.0',release:'V1.2',build:'evidence-engine-form-policy',assessmentStatus:'inconclusive',scannedAt:new Date().toISOString(),source:{url:base.href,hostname:base.hostname},identity,vertical,access,readiness,evidence,capabilities};const skill=buildSkill(report);validateReportSkillParity(report,skill);return{...report,skill}}
export default async function handler(req,res){res.setHeader('cache-control','no-store');res.setHeader('content-type','application/json; charset=utf-8');if(req.method!=='POST')return res.status(405).json({error:'Usa POST.'});try{const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):req.body||{},root=await safeUrl(body.url),home=await getText(root.href);if(!home.ok)throw Error(`Homepage non analizzabile (HTTP ${home.status}).`);const base=new URL(home.url),homeText=clean(home.text),first=collectPage(home.text,base.href);if(CHALLENGE.test(homeText)||first.facts.some(f=>f.kind==='challenge_form')){const evidence=[...first.facts,fact('access_limit','anti-bot-or-js-challenge',{source:first.facts.some(f=>f.kind==='challenge_form')?'form-structure':'http-body',url:base.href,confidence:1})];return res.status(200).json(inconclusive(base,evidence,'anti-bot-or-js-challenge'))}const children=await Promise.all(first.links.slice(0,MAX_PAGES-1).map(x=>maybe(x,800000))),pageResults=[{url:base.href,facts:first.facts},...children.filter(x=>x.ok&&(/html/i.test(x.type)||/<html\b/i.test(x.text))).map(x=>({url:x.url,...collectPage(x.text,x.url)}))],evidence=pageResults.flatMap(p=>p.facts),machine=await discoverMachine(base);evidence.push(...machine.facts);const identity=resolveIdentity(evidence,base.hostname),vertical=classifyVertical(evidence),access={status:'ok',reason:null,pagesObserved:pageResults.length},capabilities=deriveCapabilities(evidence,{pagesObserved:pageResults.length,accessStatus:'ok'}),readiness=scoreReadiness(evidence,capabilities,{accessStatus:'ok',pagesObserved:pageResults.length}),report={version:'1.2.0',release:'V1.2',build:'evidence-engine-form-policy',assessmentStatus:'complete',scannedAt:new Date().toISOString(),source:{url:base.href,hostname:base.hostname},identity,vertical,access,readiness,machineDiscovery:machine.checks,evidence,capabilities};const skill=buildSkill(report);validateReportSkillParity(report,skill);return res.status(200).json({...report,skill})}catch(e){return res.status(400).json({error:e.message||'Analisi fallita.',version:'1.2.0'})}}
